export const CONTAINER_MAX_WIDTH = '1060px'
export const ON_MOBILE = 'screen and (max-width: 48em)'
export const ON_TABLET = 'screen and (max-width: 48em)'
export const ON_DESKTOP = 'screen and (max-width: 64em)'

export const WHITE = '#ffffff'
export const VERY_LIGHT_GREY = '#e4e4e4'
export const LIGHT_GREY = '#c8c8c8'
export const GREY = '#a4a4a4'
export const HEAVY_GREY = '#777777'
export const CHARCOAL_BLACK = '#4a4a4a'
export const LINK_BLUE = '#4897d8'
export const BRIGHT_BLUE = '#337BAE'
export const ANTIQUE_BLUE = '#2d749b'
export const PRIMARY_PINK = '#f95d61'
export const DANGER_RED = '#d0021b'
export const GOOD_GREEN = '#2DB62E'

export const BASIC_OPACITY = '0.5'
